### ISSUE TITLE
Actionhero v12 has breaking changes

### ISSUE THREAD

**Issue by supamii** [S3bb1/ah-dashboard-plugin#18]
The stats object that the dashboard relies on is now a plugin - so we might want to specify that this as a hard dependency or maybe work around it.

**Comment by S3bb1** [comment]
Hi, 

i've currently creating a new Version which is compatible to AH v12. See Branch feature_adminlte2_ah12

**Comment by supamii** [comment]
I'm going to close this out - hopefully it'll be accessible via NPM as well?
