### ISSUE TITLE
npm install error - postinstall

### ISSUE THREAD

**Issue by Zougi** [S3bb1/ah-dashboard-plugin#20]
actionhero is not shipped with bower, postinstall fails, therefore npm install fails =/

workaround install bower in the actionhero project (not globally)

Tested on AH 12.2.2

**Comment by S3bb1** [comment]
Hi,

i will try to reproduce this, but i think the problem is in https://github.com/S3bb1/ah-dashboard-plugin/blob/master/package.json#L36 because this goes from the point where the "npm install" is executed. Maybe we can modify this.

Greetings

**Comment by S3bb1** [comment]
Hi,

i've tested it on windows without global installed bower and it works fine.

How you installed the dashboard ? 

With "npm install --save ah-dashboard-plugin" or with the package.json entry in the actionhero project ?

Greetings

**Comment by Zougi** [comment]
Hey S3bb1,
yeah this is the line! I'm on debian 7.

To resolve the issue I had to install bower in folder node_modules of my actionhero project with command: `npm install --save bower`

I installed ah-dashboard with command `npm install --save ah-dashboard-plugin`

A solution might be to replace
` "postinstall": "node node_modules/bower/bin/bower install" `
with
` "postinstall": "bower install" `

It doesn't change a thing I believe. postinstall should execute like npm run. It should look for bower first in the node_modules, then globaly

**Comment by Zougi** [comment]
I just made pull request https://github.com/S3bb1/ah-dashboard-plugin/pull/22 to fix the issue
Solution I found is to `npm install bower` in the postinstall script

**Comment by S3bb1** [comment]
See my comment in your pull request:


> I have temporarily added the bower components to the package with commit 2a08f22
> 
> When a build job for the frontend is available all components will be obsolete because ist concatenated in one file
