### ISSUE TITLE
Sorry, that file is not found :(

### ISSUE THREAD

**Issue by Zougi** [S3bb1/ah-dashboard-plugin#21]
Hello again,

So I'm on Debian 7, running node v5.5.0  and actionhero 12.2.2
I successfully installed the ah-dashboard-plugin with `npm install --save ah-dashboard-plugin`

My actionhero server works, it's in production, I have enabled tasks to be able to run (I use tasks in my actionhero server)

When I go to `http://localhost:8080/dashboard/index.html`

I get: `Sorry, that file is not found :(`

**Comment by S3bb1** [comment]
Hi,

do you have enabled the Plugin in the Plugins.js ?

**Comment by Zougi** [comment]
That was it!
I'm closing the issue but strongly advise to add this to the README.md, even though I guess it's in actionhero's doc
Thanks S3bb1!

**Comment by S3bb1** [comment]
Great! :) 

I will add this note to the readme :)
