### ISSUE TITLE
simple task view do not display a thing

### ISSUE THREAD

**Issue by Zougi** [S3bb1/ah-dashboard-plugin#25]
The tasks I run are just enqueu tasks I run as soon as a worker takes them.

I execute them like:
```
api.tasks.enqueu("myTask", myParameters, myQueuName, function (err, toRun) {
   //...
});
```

I do not see any task in http://mywebsite:8080/dashboard/#/tasks

Running Jobs (0)
Error: No Scheduler running!

Delayed Jobs (0)
Error: No Scheduler running!

Failed Jobs (0)
Error: No Scheduler running!

**Comment by S3bb1** [comment]
Hi,

do you have a scheduler configured ? Because the error Message says that no Scheduler is running.

**Comment by Zougi** [comment]
I didn't enable the scheduler and my server don't need to. My tasks are enqueued but I don't want them to be delayed neither to be scheduled.

**Comment by S3bb1** [comment]
You are right .. you can enqueue tasks without a scheduler at all ... i will investigate this and will change this. Maybe i can integrate the new node-resque api as well.

**Comment by S3bb1** [comment]
HI @Zougi 

i've wired the node-resque api in the tasks section. https://github.com/S3bb1/ah-dashboard-plugin/commit/2c8d109bd9c230f3ece7524598e1c697ce365e85

and it also works with a disabled scheduler ;-)

I will add realtime updates soon.

**Comment by Zougi** [comment]
Great! Thanks, I'll give it a try!

**Comment by Zougi** [comment]
@S3bb1 I just tested, it works! fyi commit 2c8d109 is not yet publish on npm ;)

**Comment by S3bb1** [comment]
Great! :) i will publish this in the next hours.
